build_from:
  amd64: ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.20
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.20
  armv7: ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.20
labels:
  io.hass.version: "2.0.0"
  io.hass.type: "addon"
  io.hass.arch: "amd64|aarch64|armv7"
